version: '3.8'

services:
  app:
    container_name: app_rentx
    build: .
    depends_on:
      - database
    tty: true
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/app
    links:
      - database

  database:
    image: postgres
    container_name: database
    restart: always
    tty: true
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=rentx_123_pass
      - POSTGRES_USER=rentx_user
      - POSTGRES_DB=rentx-base